basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: RESTful API enabling CRUD operations (Create, Read, Update, Delete)
    for user management in web application.
  license:
    name: MIT License
    url: https://github.com/HealthHub-Management-System/UserService/blob/master/LICENSE
  title: Users API
  version: "1.0"
paths:
  /../livez:
    get:
      description: Read health
      responses:
        "200":
          description: OK
      summary: Read health
      tags:
      - health
swagger: "2.0"
