basePath: /api/v1
definitions:
  error.Error:
    properties:
      error:
        type: string
    type: object
  error.Errors:
    properties:
      errors:
        items:
          type: string
        type: array
    type: object
  users.Form:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        $ref: '#/definitions/users.Role'
    type: object
  users.ListResponse:
    properties:
      users:
        items:
          $ref: '#/definitions/users.UserResponse'
        type: array
    type: object
  users.Role:
    enum:
    - unknown
    - patient
    - doctor
    - admin
    type: string
    x-enum-varnames:
    - Unknown
    - Patient
    - Doctor
    - Admin
  users.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      role:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: RESTful API enabling CRUD operations (Create, Read, Update, Delete)
    for user management in web application.
  license:
    name: MIT License
    url: https://github.com/HealthHub-Management-System/UserService/blob/master/LICENSE
  title: Users API
  version: "1.0"
paths:
  /../livez:
    get:
      description: Read health
      responses:
        "200":
          description: OK
      summary: Read health
      tags:
      - health
  /users:
    get:
      consumes:
      - application/json
      description: List users
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/users.ListResponse'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.Error'
      summary: List users
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: User form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/users.Form'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/error.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.Error'
      summary: Create user
      tags:
      - users
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.Error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.Error'
      summary: Delete user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: Read user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/users.UserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.Error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.Error'
      summary: Read user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update user
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      - description: User form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/users.Form'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.Error'
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/error.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.Error'
      summary: Update user
      tags:
      - users
swagger: "2.0"
