name: Check and test the source code
on:
  pull_request:
    branches:
    - master
    paths:
    - 'backend/**'
  workflow_dispatch:

jobs:
  test:
    name: Check the source code
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './backend'
    strategy:
      matrix:
        go-version: ['1.22.x']
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test with Go
      run: go test ./tests

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        go-version: ['1.22.x']
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.58.0
          working-directory: './backend'
          args: --timeout 3m --config .golangci-lint.yml
